### ISSUE TITLE
Cannot start the training

### ISSUE THREAD

**Issue by illusioncognitive** [chsasank/Traffic-Sign-Classification.keras#12]
I am new in machine learning. I have tried to start the training but this error came. Can anyone please help me to fix this?

**I have given this one**
`def lr_schedule(epoch):
    return lr * (0.1 ** int(epoch / 10))

batch_size = 32
epochs = 30

model.fit(X, Y,
          batch_size=batch_size,
          epochs=epochs,
          validation_split=0.2,
          callbacks=[LearningRateScheduler(lr_schedule),
                     ModelCheckpoint('model.h5', save_best_only=True)]
          )`

**And this error came**
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-9bdb640ee95d> in <module>
     10           validation_split=0.2,
     11           callbacks=[LearningRateScheduler(lr_schedule),
---> 12                      ModelCheckpoint('model.h5', save_best_only=True)]
     13           )

~/anaconda3/envs/venv/lib/python3.6/site-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
    950             sample_weight=sample_weight,
    951             class_weight=class_weight,
--> 952             batch_size=batch_size)
    953         # Prepare validation data.
    954         do_validation = False

~/anaconda3/envs/venv/lib/python3.6/site-packages/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_array_lengths, batch_size)
    749             feed_input_shapes,
    750             check_batch_axis=False,  # Don't enforce the batch size.
--> 751             exception_prefix='input')
    752 
    753         if y is not None:

~/anaconda3/envs/venv/lib/python3.6/site-packages/keras/engine/training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    126                         ': expected ' + names[i] + ' to have ' +
    127                         str(len(shape)) + ' dimensions, but got array '
--> 128                         'with shape ' + str(data_shape))
    129                 if not check_batch_axis:
    130                     data_shape = data_shape[1:]

ValueError: Error when checking input: expected conv2d_13_input to have 4 dimensions, but got array with shape (0, 1)
`

**Comment by zhaoyun0071** [comment]
你的 py主程序和你的数据集 路径问题。
小白就该这么做：
1、删除X.h5.
2、    root_dir = 'GTSRB/Final_Training/Images/'，路径改成完整路径。

**Comment by zhaoyun0071** [comment]
注意 程序和训练数据的路径，我一般都是把ipynb转换成py程序，所以py程序、GTSRB务必再同一级别目录。
然后删除X.h5，重新运行程序。
