### ISSUE TITLE
UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.

### ISSUE THREAD

**Issue by Lightyagami1** [chsasank/Traffic-Sign-Classification.keras#3]
In resize function call, constant mode needs to mentioned to suppress this warning, please update.
   In Function to preprocess the image
   under rescale to standard size part, please change

`    img = transform.resize(img, (IMG_SIZE, IMG_SIZE))`

   to

`    img = transform.resize(img, (IMG_SIZE, IMG_SIZE), mode='constant')`

**Comment by chsasank** [comment]
Thanks for raising the issue. But `mode` doesn't matter when resizing. 
The warning is because skimage is changing its default behaviour. So no need to really change, that warning will go away after a release of skimage.

**Comment by Lightyagami1** [comment]
ok, sorry to bother. :)

**Comment by qingywen** [comment]
so how to solve the problem ?

**Comment by rohun-tripathi** [comment]
In case someone is using skimage that is < 0.15, the suggestion of adding mode='constant' to resize, as mentioned above, helps suppress the  warning.

**Comment by JeasonUESTC** [comment]
@rohun-tripathi Caffe gave me the same warning when I used it, and then the program stopped running. Skimage version is 0.13, which is not a program problem. The warning was given by the python library, which has been troubling me for a long time.
I1229 07:40:40.412642  6159 net.cpp:761] Ignoring source layer afn_conf_flatten
I1229 07:40:40.412645  6159 net.cpp:761] Ignoring source layer crn_loss
/usr/local/lib/python2.7/dist-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
